In [1]:
import numpy as np

In [2]:
# generate random data

data = np.random.random((40,1000))
print(data)

[[0.23982647 0.72554858 0.99340825 ... 0.89970994 0.40546186 0.49469693]
 [0.64582292 0.43708172 0.53949405 ... 0.30547971 0.79224434 0.82615147]
 [0.7841347  0.29227642 0.02734837 ... 0.6267976  0.46990662 0.6775877 ]
 ...
 [0.95112235 0.79986696 0.12841113 ... 0.19159682 0.52222117 0.27790603]
 [0.66488943 0.1335997  0.62634616 ... 0.29360497 0.51169705 0.04644897]
 [0.88061788 0.64495053 0.89270978 ... 0.60473647 0.00936773 0.227172  ]]


In [3]:
# normalise the data
rows,col = np.shape(data)
norm_data = np.zeros(np.shape(data))
for i in range(col):
    norm_data[:,i] = (data[:,i] - min(data[:,i])/max(data[:,i]) - min(data[:,i]))

In [4]:
print(norm_data)

[[ 0.21056853  0.49544241  0.93853005 ...  0.89342449  0.39478124
   0.47608976]
 [ 0.61656498  0.20697555  0.48461585 ...  0.29919426  0.78156371
   0.8075443 ]
 [ 0.75487676  0.06217025 -0.02752984 ...  0.62051215  0.459226
   0.65898054]
 ...
 [ 0.92186441  0.56976079  0.07353293 ...  0.18531137  0.51154055
   0.25929886]
 [ 0.63563149 -0.09650647  0.57146796 ...  0.28731952  0.50101642
   0.0278418 ]
 [ 0.85135994  0.41484435  0.83783158 ...  0.59845101 -0.00131289
   0.20856483]]


In [5]:
# calculating covariance matrix of normalise data
cov_data = np.zeros(np.shape(data))
cov_data = np.cov(norm_data)

In [6]:
print(cov_data)

[[ 0.08270586  0.00619368 -0.00031765 ...  0.00225395  0.00137492
   0.00735328]
 [ 0.00619368  0.08652575  0.00213109 ... -0.0005968  -0.00210441
   0.00278341]
 [-0.00031765  0.00213109  0.07861613 ... -0.00027637  0.00034227
   0.00014626]
 ...
 [ 0.00225395 -0.0005968  -0.00027637 ...  0.08421009  0.00093299
   0.00198816]
 [ 0.00137492 -0.00210441  0.00034227 ...  0.00093299  0.08020031
   0.00382505]
 [ 0.00735328  0.00278341  0.00014626 ...  0.00198816  0.00382505
   0.08893436]]


In [7]:
# calculating eigen values and eigen vectors
eigen_val,eigen_vec = np.linalg.eig(cov_data)

In [8]:
# sorting eigen values and eigen vectors in descending order
index_eigval = np.argsort(eigen_val)

In [9]:
# sorted eigen values and eigen vectors 

# size of sorted eigen values and vectors equal to eigen values and vectors
sorted_eigval = np.zeros(np.shape(eigen_val))
sorted_eigvec = np.zeros(np.shape(eigen_vec))

# loop to length of index values of eigen values
for i in range(len(index_eigval)):
    
    sorted_eigval[len(index_eigval)-i-1] = eigen_val[index_eigval[i]]
    sorted_eigvec[:,len(index_eigval)-i-1] = eigen_vec[:,index_eigval[i]]

In [10]:
# to find cummulative weight of data 
cummulative_weight = np.zeros([len(index_eigval)])
count = 0
for i in range(len(index_eigval)):
    cummulative_weight[i] = (sorted_eigval[i] + count)/ np.sum(sorted_eigval)
    count = count + sorted_eigval[i]

In [11]:
# To check how much data we need to save 
var = 0.9
values = np.where(cummulative_weight >= 0.9)
values = values[0]
values= values[0]

selected_eigvec = sorted_eigvec[:,0:values+1]
mul_mat = selected_eigvec.transpose()

In [12]:
# to convert new data to reduced variable
new_data = np.matmul(mul_mat, data)

In [13]:
new_data.shape()

TypeError: 'tuple' object is not callable